fix #32 randomize breakage options
mozilla/shield-study-privacy pull request #43
Opened 2017-06-22 23:41 UTC by casebenton

@groovecoder how does this look? Am I performing a deep copy of the array elements correctly? 

The breakage options are shuffled everytime the report-breakage page is shown.

r?

2017-06-28 15:56 UTC, groovecoder commented
Looks good ... but when I tested I realized that we need to keep the "Something else" option at the bottom of the list. It's confusing to have:
* Something else
* Could not sign in
* Could not complete a payment

2017-06-28 15:57 UTC, groovecoder requested changes
Please preserve the "Something else" option as the last option; only shuffle the preceding options.

2017-06-28 21:12 UTC, casebenton commented
How does it look now? "something else" should always be at end now.

2017-06-29 19:56 UTC, groovecoder approved these changes

2017-06-29 19:56 UTC, merged